# Generated by Django 4.1.7 on 2023-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30, unique=True)),
                ("contact", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
