# Generated by Django 4.1.7 on 2023-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_user_member"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="member",
            table="Member",
        ),
    ]
